# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
  build:
    name: Leetcode build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.cache-name }}
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew test

  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Python packages
        uses: actions/cache@v2
        env:
          cache-name: cache-pipenv-packages
        with:
          path: |
            ~/.local/share/virtualenvs
            ~/.cache/pip
          key: ${{ runner.os }}-pipenv-${{ env.cache-name }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-${{ env.cache-name }}
            ${{ runner.os }}-pipenv-
            ${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install -d

      - name: Execute table_of_solution.py
        run: pipenv run python table_of_solutions.py

      - name: Make git commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update table of solutions in README.md
          branch: action/update-readme
          file_pattern: README.md
          push_options: --force-with-lease
          skip_dirty_check: false
